# Project information
Project: Vlast-CALO
Contact: Zhen Wang < wangz1996@sjtu.edu.cn >


Global:
    vis: False
    useseed: False # default: system time in nano-second
    seed: 100
    usemac: True # Currently not applicable
    mac: ./decay.mac
    #mac: ./secondaryproton.mac
    optical: False
    #output: ./priproton.root # Output root file name
    #output: ./secproton.root # Output root file name
    output: ./test.root # Output root file name
    beamon: 10000
    savegeo: False
    savetrack: 1
    trackEnergy_threshold: 2.0


Parameter:
    CsI:
        # Rayleigh in meter
        Rayleigh: 0.6
    TiO2:
        # Reflectivity (0~1)
        Reflectivity: 0.8
        # Absorption Length in meter
        AbsLength: 1.0
    Surface:
        # Specular reflection parameter (0~1)
        SpecularLobe: 0.8
        # Ideal specular reflection parameter (0~1)
        SpecularSpike: 0.2
        # Reflectivity (0~1)
        Reflectivity: 0.98
        #dielectric_dielectric dielectric_metal
        Type: dielectric_dielectric
        #glisur unified LUT dichroic
        Model: unified
        #polished polishedfrontpainted polishedbackpainted ground groundbackpainted polishedtioair groundtioair
        Finish: ground
        # Roughness of the surface (0~1)
        SigmaAlpha: 0.1


#Construct Tracker
Tracker:
    build: False


#Construct Converter
Converter:
    build: False
    Crystal-Nonuniformity: 0.05
    light-yield-effect: True
    E-Noise: True


#Construct Calorimeter
ECAL:
    nCryX: 1
    nCryY: 1
    ECALShield: False
    build: True
    Crystal-Nonuniformity: 0.02
    light-yield-effect: True
    E-Noise: True
    APD-Ionisation: True
    APD-distance: 5
    Digi: True


#Particle source setup
Source:
    isradio: True
    radio:
        Z: 27
        A: 60
    type: Point
    size: 15.0 # For Plane type source only (cm)
    angtype: planar
    particle: gamma
    energy: 0 # Unit is in MeV
    position: [0.0, 31.0, 0] # Unit is in mm #Converter upper plane -287.5 mm
    direction: [0.0, 0.0, 0.0]


#Verbose
Verbose:
    run: 0
    control: 0
    event: 0
    tracking: 0
