#!/bin/bash
DIR=$PWD
if [ -d jobs ];then
        rm -rf jobs;
fi
mkdir jobs
for ((i=0;i<100;i++));do
	cp -r $DIR/temp $DIR/jobs/job_$i
	sed -i "s:NUMBERHERE:100000:g" $DIR/jobs/job_$i/default.yaml
	sed -i "s:SEEDHERE:$i:g" $DIR/jobs/job_$i/default.yaml
	cd $DIR/jobs/job_$i
	#condor_submit run.condor
done
