#Project information
Project: Vlast-CALO
Contact: Zhen Wang < wangz1996@sjtu.edu.cn >


Global:
        vis: False
        useseed: False # default: system time in nano-second
        seed: 100

        usemac: False # Currently not applicable
        mac: ./primaryproton.mac
        #mac: ./secondaryproton.mac

        optical: False
        #output: ./priproton.root # Output root file name
        #output: ./secproton.root # Output root file name
        output: ./test.root # Output root file name
        beamon: 1
        savegeo: True
        savetrack: 1
        trackEnergy_threshold: 2.0
Parameter:
        CsI:
                # Rayleigh in meter
                Rayleigh: 0.6
        TiO2:
                # Reflectivity (0~1)
                Reflectivity: 0.8
                # Absorption Length in meter
                AbsLength: 1.
        Surface:
                # Specular reflection parameter (0~1)
                SpecularLobe: 0.8
                # Ideal specular reflection parameter (0~1)
                SpecularSpike: 0.2
                # Reflectivity (0~1)
                Reflectivity: 0.98
                #dielectric_dielectric dielectric_metal
                Type: dielectric_dielectric
                #glisur unified LUT dichroic
                Model: unified
                #polished polishedfrontpainted polishedbackpainted ground groundfrontpainted groundbackpainted polishedtioair groundtioair
                Finish: ground
                # Roughness of the surface (0~1)
                SigmaAlpha: 0.1
#Construct Tracker
Tracker:
        build: True
#Construct Converter
Converter:
        build: True
        Crystal-Nonuniformity: 0.05
        light-yield-effect: True
        E-Noise: True
        
#Construct Calorimeter
ECAL:
        nCryX: 5
        nCryY: 5
        ECALShield: True
        build: True
        Crystal-Nonuniformity: 0.02
        light-yield-effect: True
        E-Noise: True
        APD-Ionisation: True
        Digi: True

#Particle source setup
Source:
        type: Point
        size: 15. # For Plane type source only (cm)
        angtype: planar
        particle: gamma
        energy: 100  # Unit is in MeV
        position: [ 0., 0., -289.]   # Unit is in mm #Converter upper plane -287.5 mm
        direction: [ 0., 0., 1.]
#Verbose
Verbose:
        run: 0
        control: 0
        event: 0
        tracking: 0
