#Project information
Project: Vlast-CALO
Contact: Zhen Wang < wangz1996@sjtu.edu.cn >


Global:
        useseed: True # default: system time in nano-second
        seed: 1234

        usemac: False # Currently not applicable
        #mac: ./primaryproton.mac
        mac: ./secondaryproton.mac

        optical: False
        #output: ./priproton.root # Output root file name
        #output: ./converter.root # Output root file name
        output: ./muon_3gev.root # Output root file name
        beamon: 10000
        savegeo: False
#Construct Converter
Converter:
        build: True
#Construct Calorimeter
ECAL:
        ECALShield: True
        build: True

#Particle source setup
Source:
        particle: mu-
        energy: 3000.  # Unit is in MeV
        position: [ 0., 0., -500.]   # Unit is in mm
        direction: [ 0., 0., 1.]
#Verbose
Verbose:
        run: 0
        control: 0
        event: 0
        tracking: 0
