#Project information
Project: Vlast-CALO
Contact: Zhen Wang < wangz1996@sjtu.edu.cn >


Global:
        vis: True
        useseed: False # default: system time in nano-second
        seed: 1234

        usemac: False # Currently not applicable
        mac: ./primaryproton.mac
        #mac: ./secondaryproton.mac

        optical: True
        #output: ./priproton.root # Output root file name
        #output: ./secproton.root # Output root file name
        output: ./test.root # Output root file name
        beamon: 1
        savegeo: False

Parameter:
        CsI:
                Rayleigh: 0.6
        TiO2:
                Reflectivity: 0.8
                AbsLength: 100.
        Surface:
                SpecularLobe: 0.8
                SpecularSpike: 0.2
                Reflectivity: 0.98
                Type: dielectric_dielectric
                Model: unified
                Finish: ground
                SigmaAlpha: 0.1
#Construct Converter
Converter:
        build: True
        
#Construct Calorimeter
ECAL:
        ECALShield: False
        build: False

#Particle source setup
Source:
        particle: mu-
        energy: 3000.  # Unit is in MeV
        position: [ 0., 0., -500.]   # Unit is in mm
        direction: [ 0., 0., 1.]
#Verbose
Verbose:
        run: 0
        control: 0
        event: 0
        tracking: 0
