#!/bin/bash
energy=(20 50 100 200 300 500 800 1000 2000 3000 4000 5000)
DIR=$PWD
if [ -d jobs_4 ];then
	rm -rf jobs_4;
fi
mkdir jobs_4
for i in ${energy[@]};do
	cp -r $DIR/temp $DIR/jobs_4/$i
	cd $DIR/jobs_4/$i
	sed -i "s:EVENTNUMBERHERE:10000:g" $DIR/jobs_4/$i/default.yaml
	sed -i "s:ENERGYHERE:$i:g" $DIR/jobs_4/$i/default.yaml
	condor_submit run.condor
	cd $DIR
done
