#!/bin/bash
energy=(20 50 100 200 300 500 800 1000 2000 3000 4000 5000)
DIR=$PWD
if [ -d jobs_dr ];then
	rm -rf jobs_dr;
fi
mkdir jobs_dr
for i in ${energy[@]};do
	cp -r $DIR/temp $DIR/jobs_dr/$i
	cd $DIR/jobs_dr/$i
	sed -i "s:EVENTNUMBERHERE:100000:g" $DIR/jobs_dr/$i/default.yaml
	sed -i "s:ENERGYHERE:$i:g" $DIR/jobs_dr/$i/default.yaml
	condor_submit run.condor
	cd $DIR
done
