name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        echo "Install dependencies"
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme myst-parser


    - name: Build documentation
      run: |
        sphinx-build -b html docs/source docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
